spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=technicoDb;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: password
server:
  port: 8001
