package gr.codehub.accenture.technicoproject.enumer;

/**
 * Represents different response status.
 */
public enum ResponseStatus {
    SUCCESS,

    PROPERTY_NOT_FOUND,
    PROPERTY_NOT_CREATED,
    PROPERTY_CANNOT_BE_DELETED,
    PROPERTY_INFORMATION_IS_INCORRECT,

    PROPERTY_OWNER_NOT_FOUND,
    PROPERTY_OWNER_NOT_CREATED,
    PROPERTY_OWNER_CANNOT_BE_DELETED,
    PROPERTY_OWNER_INFORMATION_IS_INCORRECT,
    PROPERTY_OWNER_ALREADY_EXISTS,

    PROPERTY_REPAIR_ORDER_NOT_FOUND,
    PROPERTY_REPAIR_ORDER_NOT_CREATED,
    PROPERTY_REPAIR_ORDER_CANNOT_BE_DELETED,
    PROPERTY_REPAIR_ORDER_INFORMATION_IS_INCORRECT,

    NO_UPDATES_FOUND,

    ERROR
}
