package gr.codehub.accenture.technicoproject.enumer;

public enum ResponseStatus {
    SUCCESS,
    PROPERTY_OWNER_NOT_FOUND,
    PROPERTY_NOT_FOUND,
    PROPERTY_REPAIR_ORDER_NOT_FOUND,
    PROPERTY_CANNOT_BE_DELETED,
    PROPERTY_OWNER_CANNOT_BE_DELETED,
    PROPERTY_REPAIR_ORDER_CANNOT_BE_DELETED,
    PROPERTY_NOT_CREATED,
    PROPERTY_OWNER_NOT_CREATED,
    PROPERTY_REPAIR_ORDER_NOT_CREATED,
    PROPERTY_REPAIR_ORDER_CANNOT_BE_CREATED,
    PROPERTY_REPAIR_ORDER_INFORMATION_ARE_INCORRECT,
    NO_UPDATES_FOUND,
    ERROR
}
